name: Optic CI Runner
description: |
  Run Optic CI rules when your OpenAPI files change.
inputs:
  file:
    description: The OpenAPI file to evalute in this PR.
    required: true

runs:
  using: composite
  steps:
    - name: Setup
      run: |
        echo "::group::Setup"
        npm install
        echo "::endgroup::"
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
    - run: >-
        node $GITHUB_ACTION_PATH/build/index.js compare
        --from ${{ github.event.pull_request.base.sha }}:${{ inputs.file }}
        --to ${{ github.event.pull_request.head.sha }}:${{ inputs.file }}
        --github-annotations
      env:
        FORCE_COLOR: 2
      shell: bash
