name: Optic CI Runner
description: |
  Run Optic CI rules when your OpenAPI files change.
inputs:
  file:
    description: The OpenAPI file to evalute in this PR.
    required: true

runs:
  using: composite
  steps:
    - uses: bahmutov/npm-install@v1
      name: Setup
      with:
        useLockFile: false
        working-directory: ${{ github.action_path }}
    - name: Run Optic CI
      run: >-
        node ${{ github.action_path }}/node_modules/@useoptic/optic-ci/build/index compare
        --from ${{ github.event.pull_request.base.sha }}:${{ inputs.file }}
        --to ${{ github.event.pull_request.head.sha }}:${{ inputs.file }}
        --github-annotations
      env:
        FORCE_COLOR: 2
      shell: bash
